name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build & Test Node.js
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Installation de Node.js (Remplacement de Java)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Version LTS recommandée

      # Installation des dépendances
      - name: Install dependencies
        run: npm install

      # Lancement des tests (si vous en avez configuré dans package.json)
      - name: Run Tests
        run: npm test --if-present

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    # On ne pousse l'image que si c'est sur la branche main
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Connexion au Docker Hub [cite: 41, 42]
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # [cite: 44, 50]
          password: ${{ secrets.DOCKER_PASSWORD }} # [cite: 45, 50]

      # Construction et Push de l'image (Nom adapté pour nodejs)
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest

     # JOB 3 : Security Scan (Nouveau Job)
  trivy-scan:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    needs: docker # IMPORTANT : Attend que le job 'docker' soit fini
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # On se connecte pour pouvoir télécharger (pull) l'image privée/publique
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/nodejs-app:latest'
          format: 'table'
          # Mettez '0' si vous voulez que le job reste VERT même avec des failles
          # Mettez '1' si vous voulez que le job devienne ROUGE en cas de failles
          exit-code: '1' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
